// 生成静态资源内联文件（供 Edge Function 打包）
// 读取 public/ 下所有前端文件，base64 编码写入 static_content.ts
// 排除：cloudbase.full.js（废弃 SDK）、assets/（旧二维码图片）
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const PUBLIC = join(process.cwd(), 'public');
const OUT = join(process.cwd(), 'supabase/functions/mbapi/static_content.ts');
const BASE_HREF = '/functions/v1/mbapi/';

const SKIP = new Set(['cloudbase.full.js']);

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (name === 'assets') continue; // 跳过旧二维码图片
      out.push(...walk(full));
    } else {
      out.push(full);
    }
  }
  return out;
}

const files = walk(PUBLIC).filter(f => {
  const base = f.split(/[\\/]/).pop();
  return !SKIP.has(base);
});

const map = {};
for (const f of files) {
  const rel = '/' + relative(PUBLIC, f).split('\\').join('/');
  let content = readFileSync(f, 'base64');
  // HTML 注入 base href，确保所有相对路径（css/js/api）正确解析
  if (rel.endsWith('.html')) {
    const html = readFileSync(f, 'utf8');
    const injected = html.replace(/<head[^>]*>/i, m => m + `\n  <base href="${BASE_HREF}">`);
    content = Buffer.from(injected, 'utf8').toString('base64');
  }
  map[rel] = content;
  console.log('packed', rel, (Buffer.from(content, 'base64').length), 'bytes');
}

const entries = Object.entries(map)
  .map(([k, v]) => `  '${k}': '${v}',`)
  .join('\n');

const ts = `// AUTO-GENERATED by build_static.mjs — DO NOT EDIT MANUALLY
export const STATIC_FILES: Record<string, string> = {
${entries}
};
`;
writeFileSync(OUT, ts);
console.log('\\nWROTE', OUT, '-', Object.keys(map).length, 'files');
